package ris;

import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import java.sql.*;
import java.util.*;
import static java.lang.Integer.parseInt;
import java.util.logging.Level;
import java.util.logging.Logger;
import static javax.swing.JOptionPane.showMessageDialog;

public class Menu extends javax.swing.JFrame {
    
    Registered_user user; //Add value user which will set info about the logged in user (and if he is logged in)
    Connection conn;
    ArrayList<Item> items = new ArrayList<Item>();
    
    ArrayList<Favorites> favorites = new ArrayList<Favorites>(); // For the sake of testing, the favorites sql implementation is not yet added
    
    public Menu() { // Write here what to do with the window while being opened
        try{
            Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
            this.conn = DriverManager.getConnection("jdbc:ucanaccess://C:\\Users\\Dimitrije\\Downloads\\FERI_2_Letnik\\RIS\\implement\\storey.accdb");
            this.user = new Registered_user();
            System.out.println("Connected");
        }
        catch(SQLException | ClassNotFoundException e){System.out.println("fail"); e.printStackTrace();}
        catch(Exception e){System.out.println(e);}
        
        initComponents();
        setLocationRelativeTo(null); //Set the app to the center screen
    }
       
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jNavPanel = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jContentPanel = new javax.swing.JPanel();
        jHomePanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSearchPanel = new javax.swing.JPanel();
        jSearchPanel_search = new javax.swing.JPanel();
        jSearchTextField = new javax.swing.JTextField();
        jSearchButton = new javax.swing.JButton();
        jAddItemButton = new javax.swing.JButton();
        jResultPanel = new javax.swing.JPanel();
        jBackToSearchButton = new javax.swing.JButton();
        jResultScrollPane = new javax.swing.JScrollPane();
        jResultList = new javax.swing.JList<>();
        jItemPanel = new javax.swing.JPanel();
        jBackToSearchButton1 = new javax.swing.JButton();
        jFavoriteButton = new javax.swing.JButton();
        jItemNameLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jItemDetailText = new javax.swing.JTextPane();
        jAddItemPanel = new javax.swing.JPanel();
        jBackToSearchButton2 = new javax.swing.JButton();
        jItemNameTextField = new javax.swing.JTextField();
        jItemPriceTextField = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jItemDescTextArea = new javax.swing.JTextArea();
        jAvaCheckBox = new javax.swing.JCheckBox();
        jAddItemButton1 = new javax.swing.JButton();
        jProfilePanel = new javax.swing.JPanel();
        jLoginPanel = new javax.swing.JPanel();
        jRegisterLabel = new javax.swing.JLabel();
        jLoginButton = new javax.swing.JButton();
        jUsernameField1 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jRegisterPanel = new javax.swing.JPanel();
        jRegUsername = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jRegMail = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jRegPassword = new javax.swing.JPasswordField();
        jRegButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jRegPhone = new javax.swing.JTextField();
        jProfilePagePanel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Store assist - Storey");
        setMinimumSize(new java.awt.Dimension(420, 750));
        setResizable(false);
        setSize(new java.awt.Dimension(420, 750));

        jNavPanel.setLayout(new java.awt.GridLayout(1, 3, 0, 2));

        jButton1.setText("Home");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jNavPanel.add(jButton1);

        jButton2.setText("Search");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jNavPanel.add(jButton2);

        jButton3.setText("Profile");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jNavPanel.add(jButton3);

        getContentPane().add(jNavPanel, java.awt.BorderLayout.CENTER);

        jContentPanel.setLayout(new java.awt.CardLayout());

        jLabel1.setText("Home");

        javax.swing.GroupLayout jHomePanelLayout = new javax.swing.GroupLayout(jHomePanel);
        jHomePanel.setLayout(jHomePanelLayout);
        jHomePanelLayout.setHorizontalGroup(
            jHomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jHomePanelLayout.createSequentialGroup()
                .addGap(187, 187, 187)
                .addComponent(jLabel1)
                .addContainerGap(199, Short.MAX_VALUE))
        );
        jHomePanelLayout.setVerticalGroup(
            jHomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jHomePanelLayout.createSequentialGroup()
                .addGap(199, 199, 199)
                .addComponent(jLabel1)
                .addContainerGap(460, Short.MAX_VALUE))
        );

        jContentPanel.add(jHomePanel, "homecard");

        jSearchPanel.setLayout(new java.awt.CardLayout());

        jSearchTextField.setText("Item");
        jSearchTextField.setAlignmentX(1.0F);
        jSearchTextField.setPreferredSize(new java.awt.Dimension(70, 29));

        jSearchButton.setText("Search");
        jSearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSearchButtonActionPerformed(evt);
            }
        });

        jAddItemButton.setText("Add item");
        jAddItemButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAddItemButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jSearchPanel_searchLayout = new javax.swing.GroupLayout(jSearchPanel_search);
        jSearchPanel_search.setLayout(jSearchPanel_searchLayout);
        jSearchPanel_searchLayout.setHorizontalGroup(
            jSearchPanel_searchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jSearchPanel_searchLayout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addGroup(jSearchPanel_searchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSearchTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
                    .addComponent(jSearchButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(95, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jSearchPanel_searchLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jAddItemButton)
                .addContainerGap())
        );
        jSearchPanel_searchLayout.setVerticalGroup(
            jSearchPanel_searchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jSearchPanel_searchLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jAddItemButton)
                .addGap(143, 143, 143)
                .addComponent(jSearchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSearchButton)
                .addContainerGap(415, Short.MAX_VALUE))
        );

        jSearchPanel.add(jSearchPanel_search, "searchcard");

        jBackToSearchButton.setText("Back");
        jBackToSearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBackToSearchButtonActionPerformed(evt);
            }
        });

        jResultList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jResultList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jResultListMouseClicked(evt);
            }
        });
        jResultScrollPane.setViewportView(jResultList);

        javax.swing.GroupLayout jResultPanelLayout = new javax.swing.GroupLayout(jResultPanel);
        jResultPanel.setLayout(jResultPanelLayout);
        jResultPanelLayout.setHorizontalGroup(
            jResultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jResultPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jResultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jResultPanelLayout.createSequentialGroup()
                        .addComponent(jBackToSearchButton)
                        .addGap(0, 353, Short.MAX_VALUE))
                    .addComponent(jResultScrollPane))
                .addContainerGap())
        );
        jResultPanelLayout.setVerticalGroup(
            jResultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jResultPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBackToSearchButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jResultScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 629, Short.MAX_VALUE)
                .addContainerGap())
        );

        jSearchPanel.add(jResultPanel, "resultcard");

        jBackToSearchButton1.setText("Back");
        jBackToSearchButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBackToSearchButton1ActionPerformed(evt);
            }
        });

        jFavoriteButton.setText("Favorite");

        jItemNameLabel.setFont(new java.awt.Font("sansserif", 1, 36)); // NOI18N
        jItemNameLabel.setText("jLabel2");

        jScrollPane1.setViewportView(jItemDetailText);

        javax.swing.GroupLayout jItemPanelLayout = new javax.swing.GroupLayout(jItemPanel);
        jItemPanel.setLayout(jItemPanelLayout);
        jItemPanelLayout.setHorizontalGroup(
            jItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jItemPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jItemPanelLayout.createSequentialGroup()
                        .addComponent(jBackToSearchButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jFavoriteButton))
                    .addGroup(jItemPanelLayout.createSequentialGroup()
                        .addComponent(jItemNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 68, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jItemPanelLayout.setVerticalGroup(
            jItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jItemPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBackToSearchButton1)
                    .addComponent(jFavoriteButton))
                .addGap(18, 18, 18)
                .addComponent(jItemNameLabel)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 552, Short.MAX_VALUE)
                .addContainerGap())
        );

        jSearchPanel.add(jItemPanel, "itemcard");

        jBackToSearchButton2.setText("Back to search");
        jBackToSearchButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBackToSearchButton2ActionPerformed(evt);
            }
        });

        jItemNameTextField.setText("Item name");

        jItemPriceTextField.setText("Item price");

        jItemDescTextArea.setColumns(20);
        jItemDescTextArea.setRows(5);
        jItemDescTextArea.setText("Item description");
        jScrollPane2.setViewportView(jItemDescTextArea);

        jAvaCheckBox.setText("Available?");

        jAddItemButton1.setText("Add item");
        jAddItemButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAddItemButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jAddItemPanelLayout = new javax.swing.GroupLayout(jAddItemPanel);
        jAddItemPanel.setLayout(jAddItemPanelLayout);
        jAddItemPanelLayout.setHorizontalGroup(
            jAddItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jAddItemPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jAddItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jAddItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jBackToSearchButton2)
                        .addComponent(jScrollPane2)
                        .addComponent(jItemPriceTextField)
                        .addComponent(jItemNameTextField))
                    .addGroup(jAddItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jAddItemButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jAvaCheckBox, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(176, Short.MAX_VALUE))
        );
        jAddItemPanelLayout.setVerticalGroup(
            jAddItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jAddItemPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBackToSearchButton2)
                .addGap(44, 44, 44)
                .addComponent(jItemNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jItemPriceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jAvaCheckBox)
                .addGap(18, 18, 18)
                .addComponent(jAddItemButton1)
                .addContainerGap(325, Short.MAX_VALUE))
        );

        jSearchPanel.add(jAddItemPanel, "additemcard");

        jContentPanel.add(jSearchPanel, "searchcard");

        jProfilePanel.setLayout(new java.awt.CardLayout());

        jRegisterLabel.setText("Register");
        jRegisterLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jRegisterLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRegisterLabelMouseClicked(evt);
            }
        });

        jLoginButton.setText("Login");
        jLoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLoginButtonActionPerformed(evt);
            }
        });

        jUsernameField1.setText("Username");

        jPasswordField1.setText("password");

        javax.swing.GroupLayout jLoginPanelLayout = new javax.swing.GroupLayout(jLoginPanel);
        jLoginPanel.setLayout(jLoginPanelLayout);
        jLoginPanelLayout.setHorizontalGroup(
            jLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLoginPanelLayout.createSequentialGroup()
                .addContainerGap(123, Short.MAX_VALUE)
                .addGroup(jLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jRegisterLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLoginPanelLayout.createSequentialGroup()
                        .addComponent(jLoginButton)
                        .addGap(59, 59, 59))
                    .addComponent(jUsernameField1, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                    .addComponent(jPasswordField1))
                .addGap(117, 117, 117))
        );
        jLoginPanelLayout.setVerticalGroup(
            jLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLoginPanelLayout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addComponent(jUsernameField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLoginButton)
                .addGap(18, 18, 18)
                .addComponent(jRegisterLabel)
                .addContainerGap(382, Short.MAX_VALUE))
        );

        jProfilePanel.add(jLoginPanel, "logincard");

        jRegUsername.setText("Enter a username");

        jLabel2.setText("Username");

        jLabel3.setText("Mail");

        jRegMail.setText("Enter a mail");

        jLabel4.setText("Password");

        jRegPassword.setText("jPasswordField2");

        jRegButton.setText("Register");
        jRegButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRegButtonActionPerformed(evt);
            }
        });

        jLabel5.setText("Phone");

        jRegPhone.setText("jTextField2");

        javax.swing.GroupLayout jRegisterPanelLayout = new javax.swing.GroupLayout(jRegisterPanel);
        jRegisterPanel.setLayout(jRegisterPanelLayout);
        jRegisterPanelLayout.setHorizontalGroup(
            jRegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jRegisterPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jRegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRegUsername)
                    .addComponent(jRegMail, javax.swing.GroupLayout.DEFAULT_SIZE, 408, Short.MAX_VALUE)
                    .addComponent(jRegPassword)
                    .addGroup(jRegisterPanelLayout.createSequentialGroup()
                        .addGroup(jRegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jRegButton)
                            .addComponent(jLabel5))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jRegPhone))
                .addContainerGap())
        );
        jRegisterPanelLayout.setVerticalGroup(
            jRegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jRegisterPanelLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRegUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRegMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRegPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRegPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRegButton)
                .addContainerGap(348, Short.MAX_VALUE))
        );

        jProfilePanel.add(jRegisterPanel, "registercard");

        jLabel6.setFont(new java.awt.Font("sansserif", 0, 36)); // NOI18N
        jLabel6.setText("jLabel6");

        javax.swing.GroupLayout jProfilePagePanelLayout = new javax.swing.GroupLayout(jProfilePagePanel);
        jProfilePagePanel.setLayout(jProfilePagePanelLayout);
        jProfilePagePanelLayout.setHorizontalGroup(
            jProfilePagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jProfilePagePanelLayout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addComponent(jLabel6)
                .addContainerGap(160, Short.MAX_VALUE))
        );
        jProfilePagePanelLayout.setVerticalGroup(
            jProfilePagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jProfilePagePanelLayout.createSequentialGroup()
                .addGap(216, 216, 216)
                .addComponent(jLabel6)
                .addContainerGap(412, Short.MAX_VALUE))
        );

        jProfilePanel.add(jProfilePagePanel, "profilecard");

        jContentPanel.add(jProfilePanel, "profilecard");

        getContentPane().add(jContentPanel, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        CardLayout card = (CardLayout)jContentPanel.getLayout();
        card.show(jContentPanel, "homecard");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        CardLayout card = (CardLayout)jContentPanel.getLayout();
        card.show(jContentPanel, "searchcard");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        CardLayout card = (CardLayout)jContentPanel.getLayout();
        card.show(jContentPanel, "profilecard");
        
        CardLayout card1 = (CardLayout)jProfilePanel.getLayout();
        
        if(user.isLogged()){card1.show(jProfilePanel, "profilecard");}else{card1.show(jProfilePanel, "logincard");} 
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jSearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSearchButtonActionPerformed
        
        String sTerm = jSearchTextField.getText();
        
        try {            
            String q = "SELECT * FROM Item WHERE itemName LIKE '%" + sTerm+"%'";
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery(q);
            
            if (!rs.isBeforeFirst() ) {    
                showMessageDialog(null, "Search term returned no results");
            } else{
            
            items.clear();
            while(rs.next()){
                Item item = new Item(rs.getInt("ID"),rs.getString("itemName"),rs.getInt("price"),rs.getString("description"),rs.getBoolean("availability"));
                items.add(item);
            }
            
            DefaultListModel listModel = new DefaultListModel();
            for (int i = 0; i < items.size(); i++)
            {
                listModel.addElement(items.get(i).getId() + " - " + items.get(i).getName());
            }
            
            jResultList.setModel(listModel);
            
            CardLayout card = (CardLayout)jSearchPanel.getLayout();
            card.show(jSearchPanel, "resultcard");
        }} 
        catch(SQLException e){System.out.println("fail"); e.printStackTrace();}
        catch(Exception e){System.out.println(e);}
    }//GEN-LAST:event_jSearchButtonActionPerformed

    private void jBackToSearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBackToSearchButtonActionPerformed
        CardLayout card = (CardLayout)jSearchPanel.getLayout();
        card.show(jSearchPanel, "searchcard");
    }//GEN-LAST:event_jBackToSearchButtonActionPerformed

    private void jResultListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jResultListMouseClicked
        JList list = (JList)evt.getSource();
        if(evt.getClickCount() == 2){
            
            int index = list.locationToIndex(evt.getPoint());
            Item item = items.get(index);
            
            itemDetail(item);
            CardLayout card = (CardLayout)jSearchPanel.getLayout();
            card.show(jSearchPanel, "itemcard");
            
            ActionListener[] listeners = jFavoriteButton.getActionListeners();
            if (listeners.length != 0){
                for(ActionListener al:listeners){
                    jFavoriteButton.removeActionListener( al );
                }
            }
            
            boolean existsfavorite = false;
            jFavoriteButton.setText("Favorite");
            
            for (int i = 0; i < favorites.size(); i++) { // This for loop could also be enchanced
                if (favorites.get(i).getUserId() == user.getId()) {
                    for (Item item1 : favorites.get(i).getItems()) {
                        if (item1.getId() == items.get(index).getId()) {
                            existsfavorite = true;
                            jFavoriteButton.setText("Remove favorite");
                            break;
                        }
                    }
                    break;
                }
            }
            
            if (!existsfavorite) {
            jFavoriteButton.addActionListener(new ActionListener(){
                @Override
                public void actionPerformed(ActionEvent ae) {
                    if(user.isLogged()){
                        boolean existsitem = false;
                        boolean exists = false;
                        
                        for (int i = 0; i < favorites.size(); i++) {  // This for loop could be enchanced
                            if (favorites.get(i).getUserId() == user.getId()) {
                                for (Item item1 : favorites.get(i).getItems()) {
                                    if (item1.getId() == items.get(index).getId()) {
                                        showMessageDialog(null, "The item is already favorited");
                                        existsitem = true;
                                        break;
                                    }
                                    
                                }
                            
                                if(!existsitem){
                                 favorites.get(i).addItem(items.get(index));
                                 jFavoriteButton.setText("Remove favorite");
                                 showMessageDialog(null, "Item successfully favorited");
                                }
                                exists = true;
                                break;    
                            }
                        }
                        if(!exists){
                            Favorites favorites1 = new Favorites(user.getId());
                            favorites1.addItem(items.get(index));
                            favorites.add(favorites1);
                            jFavoriteButton.setText("Remove favorite");
                            showMessageDialog(null, "Item successfully favorited");
                        }
                        
                    } else{showMessageDialog(null, "Please log in");}
                }
            });
            }
        }
    }//GEN-LAST:event_jResultListMouseClicked

    private void jBackToSearchButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBackToSearchButton1ActionPerformed
        CardLayout card = (CardLayout)jSearchPanel.getLayout();
        card.show(jSearchPanel, "searchcard");
    }//GEN-LAST:event_jBackToSearchButton1ActionPerformed

    private void jRegisterLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRegisterLabelMouseClicked
        CardLayout card = (CardLayout)jProfilePanel.getLayout();
        card.show(jProfilePanel, "registercard");
    }//GEN-LAST:event_jRegisterLabelMouseClicked

    private void jLoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLoginButtonActionPerformed
        
        String usern = jUsernameField1.getText();
        String pass = jPasswordField1.getText();
        
        try {            
            String q = "SELECT * FROM User WHERE username = '" + usern + "'";
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery(q);
            
            if (!rs.isBeforeFirst() ) {    
                showMessageDialog(null, "Username doesn't exist");
            } else{
            
            int id = 0;    
            String username = "";
            String mail = "";
            String password = "";
            String phone = "";
                
            while(rs.next()) {
                id = rs.getInt("ID");
                username = rs.getString("username");
                mail = rs.getString("mail");
                phone = rs.getString("phone");
                password = rs.getString("password");
            }    
                
            if (password.equals(pass)){
                this.user.logIn(id,username, mail, phone, password);
                showMessageDialog(null, "Logged in successfully!");
                jLabel6.setText(user.getUsername());
            } else{
                showMessageDialog(null, "Wrong password");
            }
            
            CardLayout card = (CardLayout)jContentPanel.getLayout();
            card.show(jContentPanel, "homecard");
        }} 
        catch(SQLException e){System.out.println("fail"); e.printStackTrace();}
        catch(Exception e){System.out.println(e);}
    }//GEN-LAST:event_jLoginButtonActionPerformed

    private void jAddItemButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAddItemButtonActionPerformed
        CardLayout card = (CardLayout)jSearchPanel.getLayout();
        card.show(jSearchPanel, "additemcard");
    }//GEN-LAST:event_jAddItemButtonActionPerformed

    private void jBackToSearchButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBackToSearchButton2ActionPerformed
        CardLayout card = (CardLayout)jSearchPanel.getLayout();
        card.show(jSearchPanel, "searchcard");
    }//GEN-LAST:event_jBackToSearchButton2ActionPerformed

    private void jAddItemButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAddItemButton1ActionPerformed
        try{    // This is to check whether the price has been entered corrctly (in form of a number
            
        String name = jItemNameTextField.getText();
        int price = parseInt(jItemPriceTextField.getText());
        String desc = jItemDescTextArea.getText();
        boolean ava = jAvaCheckBox.isEnabled();
        
        int id1 = 0;
        
        try{
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery("SELECT * FROM Item");
            
            while(rs.next()) {
               if(rs.isLast()) {
                    id1 = rs.getInt("ID");
                }
            }
        }catch(Exception e){System.out.println(e);}
        
        id1++;
        
        try {
        String q = "INSERT INTO Item ([ID],[itemName],[price],[description],[availability]) VALUES (?,?,?,?,?)";
        PreparedStatement st = conn.prepareStatement(q);
            st.setInt(1,id1);
            st.setString(2,name);
            st.setInt(3,price);
            st.setString(4,desc);
            st.setBoolean(5,ava);
            st.executeUpdate();
        } catch (SQLException ex) {Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);}
        
        showMessageDialog(null, "Item uploaded successfully");
        
        Item item = new Item(id1,name,price,desc,ava);
        }catch(Exception e){
                showMessageDialog(null, "Please input the price correctly"); 
            }
    }//GEN-LAST:event_jAddItemButton1ActionPerformed

    private void jRegButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRegButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRegButtonActionPerformed

    private void itemDetail(Item item){
        
        jItemNameLabel.setText(item.getName());
        
        jItemDetailText.setText(item.toString());
    }    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() { // When the app runs
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jAddItemButton;
    private javax.swing.JButton jAddItemButton1;
    private javax.swing.JPanel jAddItemPanel;
    private javax.swing.JCheckBox jAvaCheckBox;
    private javax.swing.JButton jBackToSearchButton;
    private javax.swing.JButton jBackToSearchButton1;
    private javax.swing.JButton jBackToSearchButton2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel jContentPanel;
    private javax.swing.JButton jFavoriteButton;
    private javax.swing.JPanel jHomePanel;
    private javax.swing.JTextArea jItemDescTextArea;
    private javax.swing.JTextPane jItemDetailText;
    private javax.swing.JLabel jItemNameLabel;
    private javax.swing.JTextField jItemNameTextField;
    private javax.swing.JPanel jItemPanel;
    private javax.swing.JTextField jItemPriceTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton jLoginButton;
    private javax.swing.JPanel jLoginPanel;
    private javax.swing.JPanel jNavPanel;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPanel jProfilePagePanel;
    private javax.swing.JPanel jProfilePanel;
    private javax.swing.JButton jRegButton;
    private javax.swing.JTextField jRegMail;
    private javax.swing.JPasswordField jRegPassword;
    private javax.swing.JTextField jRegPhone;
    private javax.swing.JTextField jRegUsername;
    private javax.swing.JLabel jRegisterLabel;
    private javax.swing.JPanel jRegisterPanel;
    private javax.swing.JList<String> jResultList;
    private javax.swing.JPanel jResultPanel;
    private javax.swing.JScrollPane jResultScrollPane;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jSearchButton;
    private javax.swing.JPanel jSearchPanel;
    private javax.swing.JPanel jSearchPanel_search;
    private javax.swing.JTextField jSearchTextField;
    private javax.swing.JTextField jUsernameField1;
    // End of variables declaration//GEN-END:variables
}
